# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alistairmccann
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: todos
# "service" is the name of this project. This will also be added to your AWS resource names.
service: todo-dynamodb

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
